Retail checkout
TexasInstruments/edgeai-gst-apps-retail-checkout pull request #1
Opened 2023-04-04 15:03 UTC by reesegrimsley

Retail demo from EW 2023 with supporting READMEs (how to run, how it's made, and a small FAQ). Application is in retail-shopping directory, rather than extending apps_python (which would require a non-trivial refactor).

2023-04-05 21:40 UTC, shyam-j requested changes
1. Try not to check-in IMX219 DCC binary files these will be present under /opt/imaging/imx219
2. Avoid checking in models in these repos, we can host them on dl-stage, ill send the location. You can have a script which downloads the model from dl-stage. 
3. Keep the repo lite with just source files, scripts and documentation in general

2023-04-06 13:25 UTC, reesegrimsley commented
In response to shyam-j's comment:
1. The IMX219 DCC files had to be regenerated for this resolution. The ones already present do not work for the configuration used in this project
2. Once I have that model pushed, tested, and README's modified, I will push update commit
3. Please mention if there are specific files that should not be included. IMX219 files are necessary and model files can be removed. The rest should only be source code in Python, scripts, and documentation (markdown files and supporting images)

2023-04-11 04:28 UTC, ravi-rahul commented on retail-shopping/camera-imx219/setup_imx219-1640x1232.sh
> +
Hi @reesegrimsley 

I suggest you modify the **scripts/setup_camera.sh** script it self.
since this is not deviated much from the original script

2023-04-11 22:21 UTC, reesegrimsley commented
I've made changes aligned with those requested above. The model is still hosted within this repo. Until we have a solution on where to host that, I'd like to request we merge this change to prevent it from holding up other documentation that needs to link to the source code here.

2023-04-13 20:30 UTC, reesegrimsley commented
All requested changes have been implemented as listed below. Commits are all squashed into a single one following the last 'main' branch commit and force-pushed.
- remove custom files for imx219 and setup script. Modify the ./scripts/setup_cameras.sh script to use th 1640x1232 RGGB10 format
- Remove the compiled model 
- Add download scripts for the model and the labelled dataset (no augmentation)

Ready to merge from my perspective!

2023-04-14 05:08 UTC, ravi-rahul approved these changes

2023-04-18 13:05 UTC, merged